### ISSUE TITLE
Publish Bio::Variation::* to CPAN

### ISSUE THREAD

**Issue by sunpoet** [bioperl/Bio-Variation#2]
Hi,

Since Bio::Variation::* was removed from BioPerl 1.7.3+, could you please publish it to CPAN so that Bio::Variation::SNP (dependency of Bio::Cluster) is available there.
Thanks!

**Comment by dbevans** [comment]
> Hi,
> 
> Since Bio::Variation::* was removed from BioPerl 1.7.3+, could you please publish it to CPAN so that Bio::Variation::SNP (dependency of Bio::Cluster) is available there.
> Thanks!




Seconded.  Any progress?

**Comment by mr-c** [comment]
Another vote; we need this for Debian; thanks!

**Comment by carandraug** [comment]
If someone is interested in taking in maintenance of the Bio-Variation distribution, leave a comment. It doesn't look like any of the current maintainers of BioPerl has the time to do so.

**Comment by tillea** [comment]
I have no intend to work on this - but I agree with @mr-c that it would be important to keep all functionality we currently have in Debian.

**Comment by mr-c** [comment]
This is needed for `lib/Bio/ClusterIO/dbsnp.pm` and `Bio::Cluster` is a requirement of `Bio::ASN1::EntrezGene` which is a requirement of `Bio::DB::NCBIHelper` which is a requirement of `Bio::Procedural` which is the new home for the `Bio::Perl` newbie module, so it would be nice to have this released to CPAN.

Maybe @cjfields can help again?

Many thanks to all who help maintain these packages.

**Comment by cjfields** [comment]
We need a road map for the dependencies (though @carandraug and I anticipated some of this). Will see if we can push something quick.

**Comment by cjfields** [comment]
@mr-c I pushed out a release that appears to have indexed on CPAN.  I'd give a day or two just in case issues pop up on tests, though local ones ran fine.

**Comment by sunpoet** [comment]
@cjfields Thanks! I've [ported it to FreeBSD](https://svnweb.freebsd.org/changeset/ports/519320).

**Comment by cjfields** [comment]
Not a problem @sunpoet . @mr-c looks like the testing is clean:

http://matrix.cpantesters.org/?dist=Bio-Variation+1.7.4

It should be good to go for Debian, reopen this ticket if any issues pop up!

**Comment by mr-c** [comment]
@cjfields Got it, thanks!
