### ISSUE TITLE
Recursive dependency

### ISSUE THREAD

**Issue by chorny** [bioperl/Bio-Variation#3]
```
Recursive dependency detected:
    Bio::Variation::SNP (have: N/A; want: 1.007004)
 => CJFIELDS/Bio-Variation-1.7.4.tar.gz
 => Bio::DB::GenBank (have: N/A; requires: 0)
 => CJFIELDS/Bio-DB-NCBIHelper-1.7.6.tar.gz
 => Bio::SeqIO::entrezgene (have: N/A; requires: 0)
 => CJFIELDS/Bio-ASN1-EntrezGene-1.73.tar.gz
 => Bio::Cluster::SequenceFamily (have: N/A; requires: 0)
 => CJFIELDS/Bio-Cluster-1.7.3.tar.gz
 => Bio::Variation::SNP (have: N/A; requires: 0).
```

**Comment by cjfields** [comment]
See also https://github.com/bioperl/bioperl-live/issues/331

**Comment by cjfields** [comment]
We'll have to trace through this and see specifically where we can break this dependency.  If it's only for tests this could be set up for running in dev-only mode.

**Comment by carandraug** [comment]
The dependency on `Bio::DB::GenBank` and `Bio::DB::EMBL` is for the `bp_flanks` program so it can be called with an accession number instead of a file.

**Comment by cjfields** [comment]
@carandraug ah, makes sense.  Question is how to disentangle this; any recommendations?

**Comment by carandraug** [comment]
One suggestion is to make the class to use an argument to `bp_flanks`. This makes it a separate dependency, it makes a dependency that the user must explicity name, and also enables `bp_flanks` to work with any class that implements a specific interface.

**Comment by cjfields** [comment]
@carandraug seems like a reasonable solution.  I did notice that the script doesn't actually use `Bio::Variation` modules, it is primarily used for extracting flanking regions for any list of positions (the most obvious case being variants) from local or remote sequence records.  Any reason it's in this dist beyond it involving variants?

**Comment by carandraug** [comment]
The commit messages https://github.com/bioperl/bioperl-live/commit/1f7b54a281a82e54767a878f7a46f3dd4c664447 says:

> Bio::Variation::* move namespace into its own distribution.
>
> Also move the program bin_flanks which although not actually using the
> Bio::Variation modules, it's to be used in the same context.

**Comment by cjfields** [comment]
@carandraug works for me (makes sense to do so, just wanted to make sure).

**Comment by cjfields** [comment]
Pushing out a new point release (1.7.5), will see if this addresses the problem.

**Comment by carandraug** [comment]
The change in  d3a1dcc is really not what I suggested. But if you want to go that way, you might was well not change the code and list those two modules as dependencies to ignore on `dist.ini` with `AutoPrereqs.skips` (see bioperl-live `dist.ini` for an example)

**Comment by carandraug** [comment]
> [...] you might was well not change the code [...]

Well, you would only need to change the `use` to a `require` within the right block.

**Comment by cjfields** [comment]
> Well, you would only need to change the use to a require within the right block.

The fix was a bit low-hanging fruit but using the BioPerl API, we could switch it to a simple `eval "require $class"` or similar.  

There will be instances where installing this distribution directly will fail with the auto-generated `t/00-compile.t` tests, see: http://www.cpantesters.org/cpan/report/1dcbc584-209d-11ea-99fe-b031dbec7dbf.  Not sure if ignoring within `dist.ini` fixes this?
